[colors]
foreground = "#474747"
background = "#ffffff"
cursor_bg = "#474747"
cursor_border = "#474747"
cursor_fg = "#ffffff"
selection_bg = "#cccccf"
selection_fg = "#474747"
split = "#277add"
compose_cursor = "#aa5b00"
scrollbar_thumb = "#f7f7f7"

ansi = ["#cccccc", "#e30000", "#5e774c", "#8e5600", "#4782a8", "#ec008f", "#3b888f", "#5a5a5a"]
brights = ["#fefefe", "#fb0000", "#618741", "#9f6100", "#2991c5", "#ff1d9d", "#0499a2", "#474747"]

[colors.tab_bar]
inactive_tab_edge = "#ededed"
background = "#ffffff"

[colors.tab_bar.active_tab]
fg_color = "#ededed"
bg_color = "#277add"

[colors.tab_bar.inactive_tab]
fg_color = "#8990b3"
bg_color = "#f7f7f7"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#277add"
bg_color = "#f7f7f7"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#277add"
bg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#277add"
bg_color = "#ffffff"

[metadata]
aliases = []
author = "falcon"
name = "tasogare_light"