[colors]
foreground = "#ffffff"
background = "#000000"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#2b2b30"
selection_fg = "#ffffff"
split = "#82aaf9"
compose_cursor = "#ffa56e"
scrollbar_thumb = "#0a0a0d"

ansi = ["#000000", "#ff9f9f", "#9fc682", "#ffc294", "#61afe1", "#ff7eb6", "#50b4be", "#dddddd"]
brights = ["#010101", "#ffb4b4", "#9fd96c", "#ffd4b8", "#58befa", "#ff96c1", "#03c6d3", "#ffffff"]

[colors.tab_bar]
inactive_tab_edge = "#000000"
background = "#000000"

[colors.tab_bar.active_tab]
fg_color = "#000000"
bg_color = "#82aaf9"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#0a0a0d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#82aaf9"
bg_color = "#0a0a0d"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#82aaf9"
bg_color = "#000000"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#82aaf9"
bg_color = "#000000"

[metadata]
aliases = []
author = "falcon"
name = "tasogare_dark"