# tasogare Alacritty Colors
# Default colors
[colors.primary]
background = '#ffffff'
foreground = '#474747'

#[colors.cursor]
#cursor = '#474747'
#text = '#ffffff'

# Normal colors
[colors.normal]
black = '#cccccc'
red = '#f12465'
green = '#56713a'
yellow = '#85683f'
blue = '#277add'
magenta = '#9a4af3'
cyan = '#006d8f'
white = '#5a5a5a'

# Bright colors
[colors.bright]
black = '#fefefe'
red = '#f12465'
green = '#56713a'
yellow = '#85683f'
blue = '#277add'
magenta = '#9a4af3'
cyan = '#006d8f'
white = '#474747'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#aa5b00'

[[colors.indexed_colors]]
index = 17
color = '#c64343'

