# tasogare Alacritty Colors
# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

#[colors.cursor]
#cursor = '#ffffff'
#text = '#000000'

# Normal colors
[colors.normal]
black = '#000000'
red = '#f97e96'
green = '#a4d472'
yellow = '#e6b672'
blue = '#82aaf9'
magenta = '#c1a0f9'
cyan = '#85d5ff'
white = '#dddddd'

# Bright colors
[colors.bright]
black = '#010101'
red = '#f97e96'
green = '#a4d472'
yellow = '#e6b672'
blue = '#82aaf9'
magenta = '#c1a0f9'
cyan = '#85d5ff'
white = '#ffffff'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ffa56e'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

