[[themes]]
name = "Tokyo Night Light"
[themes.palette]
background = "#ededed"
foreground = "#5a5a5a"
black = "#fefefe"
red = "#f12465"
green = "#56713a"
yellow = "#85683f"
blue = "#277add"
magenta = "#9a4af3"
cyan = "#006d8f"
white = "${white}"
bright_black = "#ffffff"
bright_red = "#c64343"
bright_green = "#387068"
bright_yellow = "#aa5b00"
bright_blue = "#188092"
bright_magenta = "#d20065"
bright_cyan = "#006a83"
bright_white = "#474747"
