[[themes]]
name = "Tokyo Night"
[themes.palette]
background = "#000000"
foreground = "#dddddd"
black = "#010101"
red = "#f97e96"
green = "#a4d472"
yellow = "#e6b672"
blue = "#82aaf9"
magenta = "#c1a0f9"
cyan = "#85d5ff"
white = "${white}"
bright_black = "#000000"
bright_red = "#db4b4b"
bright_green = "#73daca"
bright_yellow = "#ffa56e"
bright_blue = "#2ac3de"
bright_magenta = "#ff007c"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
