attribute = { fg = "#b25ccb" }
comment = { fg = "#7c7c84", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#7f5c00" }
constant = { fg = "#5e774c" }
"constant.builtin" = { fg = "#005e65" }
"constant.builtin.boolean" = { fg = "#5e774c" }
"constant.character" = { fg = "#5e774c" }
"constant.character.escape" = { fg = "#b25ccb" }
"constant.numeric" = { fg = "#5e774c" }
"constant.numeric.float" = { fg = "#5e774c" }
"constant.numeric.integer" = { fg = "#5e774c" }
constructor = { fg = "#ad00ca" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#496087" }
"diff.delta.moved" = { fg = "#0076cd" }
"diff.minus" = { fg = "#ec5c5e" }
"diff.plus" = { fg = "#0e7337" }
error = { fg = "#c64343" }
function = { fg = "#8e5600" }
"function.builtin" = { fg = "#005e65" }
"function.macro" = { fg = "#8e5600" }
"function.method" = { fg = "#8e5600" }
"function.special" = { fg = "#b25ccb" }
hint = { fg = "#118c74" }
info = { fg = "#3a7aa3" }
keyword = { fg = "#006ca2", modifiers = ["italic"] }
"keyword.control" = { fg = "#0076cd" }
"keyword.control.conditional" = { fg = "#0076cd" }
"keyword.control.exception" = { fg = "#0076cd" }
"keyword.control.repeat" = { fg = "#0076cd" }
"keyword.control.return" = { fg = "#006ca2", modifiers = ["italic"] }
"keyword.directive" = { fg = "#b25ccb" }
"keyword.function" = { fg = "#8e5600" }
"keyword.operator" = { fg = "#0076cd" }
label = { fg = "#727272" }
"markup.bold" = { fg = "#474747", modifiers = ["bold"] }
"markup.heading" = { fg = "#4782a8", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#020202", fg = "#474747" }
"markup.heading.hover" = { bg = "#ceced0" }
"markup.italic" = { fg = "#474747", modifiers = ["italic"] }
"markup.link" = { fg = "#4782a8" }
"markup.link.label" = { fg = "#005e65" }
"markup.link.text" = { fg = "#4782a8" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#006500" }
"markup.normal.completion" = { fg = "#98989f" }
"markup.normal.hover" = { fg = "#7f7f8b" }
"markup.raw" = { fg = "#5e774c" }
"markup.raw.inline" = { bg = "#fefefe", fg = "#0076cd" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#ad00ca" }
operator = { fg = "#4b606b" }
special = { fg = "#005e65" }
string = { fg = "#5e774c" }
"string.regexp" = { fg = "#3b888f" }
"string.special" = { fg = "#005e65" }
tag = { fg = "#0076cd" }
type = { fg = "#ad00ca" }
"type.builtin" = { fg = "#bd33d5" }
"type.enum" = { fg = "#ad00ca" }
"type.enum.variant" = { fg = "#5e774c" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#474747", fg = "#ffffff" }
"ui.cursor.match" = { fg = "#7d5600", modifiers = ["bold"] }
"ui.linenr" = { fg = "#9d9da3" }
"ui.linenr.select" = { fg = "#005a87", modifiers = ["bold"] }
"ui.menu" = { bg = "#020202", fg = "#474747" }
"ui.menu.scroll" = { bg = 328965, fg = 10329507 }
"ui.menu.selected" = { bg = "#ceced0" }
"ui.popup" = { bg = "#020202", fg = "#afafb6" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#ffffff", fg = "#5a5a5a" }
"ui.statusline.inactive" = { bg = "#ffffff", fg = "#9d9da3" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#ffffff", fg = "#474747" }
"ui.text.focus" = { bg = "#cccccf" }
"ui.text.inactive" = { fg = "#7c7c84", modifiers = ["italic"] }
"ui.text.info" = { bg = "#020202", fg = "#474747" }
"ui.virtual.inlay-hint" = { bg = "#e7f4f1", fg = "#118c74" }
"ui.window" = { fg = "#b3b3b7", modifiers = ["bold"] }
variable = { fg = "#474747" }
"variable.builtin" = { fg = "#006ca2" }
"variable.other.member" = { fg = "#e30000" }
"variable.parameter" = { fg = "#005e65" }
warning = { fg = "#b96e00" }

[palette]
bg = "#ffffff"
bg_dark = "#ededed"
bg_float = "#020202"
bg_highlight = "#f7f7f7"
bg_popup = "#020202"
bg_search = "#7890dd"
bg_sidebar = "#020202"
bg_statusline = "#ffffff"
bg_visual = "#cccccf"
black = "#cccccc"
blue = "#277add"
blue0 = "#7890dd"
blue1 = "#188092"
blue2 = "#07879d"
blue5 = "#006a83"
blue6 = "#2e5857"
blue7 = "#92a6d5"
border = "#b3b3b7"
border_highlight = "#afafb6"
color1 = "#006ca2"
color10 = "#b25ccb"
color11 = "#727272"
color12 = "#4b606b"
color13 = "#8e5600"
color14 = "#e30000"
color15 = "#7d7918"
color16 = "#006500"
color17 = "#7d5600"
color18 = "#005e65"
color19 = "#525a64"
color2 = "#ad00ca"
color20 = "#3a7aa3"
color21 = "#006b00"
color22 = "#95bbc8"
color23 = "#be4e7f"
color24 = "#bac4dd"
color25 = "#7f5c00"
color26 = "#ec008f"
color27 = "#005a87"
color28 = "#4f72be"
color29 = "#118c74"
color3 = "#5e774c"
color30 = "#0076cd"
color4 = "#3b888f"
color5 = "#6e6e6e"
color6 = "#7f724e"
color7 = "#4782a8"
color8 = "#b96e00"
color9 = "#d5375e"
comment = "#87a5b6"
cyan = "#006d8f"
dark3 = "#8990b3"
dark5 = "#68709a"
"diff.add" = "#80b280"
"diff.change" = "#a3c1d4"
"diff.delete" = "#ea9baf"
"diff.text" = "#4782a8"
error = "#c64343"
fg = "#474747"
fg_dark = "#5a5a5a"
fg_float = "#474747"
fg_gutter = "#9d9da3"
fg_sidebar = "#5a5a5a"
"git.add" = "#0e7337"
"git.change" = "#496087"
"git.delete" = "#ec5c5e"
"git.ignore" = "#8990b3"
gray = "#777777"
gray0 = "#e1e1e3"
gray1 = "#ceced0"
gray2 = "#b3b3b7"
gray3 = "#98989f"
gray4 = "#7c7c84"
gray5 = "#7f7f8b"
gray6 = "#5e5e6c"
gray7 = "#555566"
green = "#56713a"
green1 = "#387068"
green2 = "#38919f"
hint = "#118c74"
info = "#3a7aa3"
magenta = "#9a4af3"
magenta2 = "#d20065"
orange = "#aa5b00"
purple = "#7847bd"
rainbow = "#4f72be"
"rainbow.2" = "#7f5c00"
"rainbow.3" = "#006500"
"rainbow.4" = "#118c74"
"rainbow.5" = "#ad00ca"
"rainbow.6" = "#b25ccb"
red = "#f12465"
red1 = "#c64343"
teal = "#118c74"
"terminal.black" = "#cccccc"
"terminal.black_bright" = "#fefefe"
"terminal.blue" = "#4782a8"
"terminal.blue_bright" = "#2991c5"
"terminal.cyan" = "#3b888f"
"terminal.cyan_bright" = "#0499a2"
"terminal.green" = "#5e774c"
"terminal.green_bright" = "#618741"
"terminal.magenta" = "#ec008f"
"terminal.magenta_bright" = "#ff1d9d"
"terminal.red" = "#e30000"
"terminal.red_bright" = "#fb0000"
"terminal.white" = "#5a5a5a"
"terminal.white_bright" = "#474747"
"terminal.yellow" = "#8e5600"
"terminal.yellow_bright" = "#9f6100"
terminal_black = "#fefefe"
todo = "#277add"
warning = "#b96e00"
yellow = "#85683f"