[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#5a5a5a", italic = true }

# Hovered
hovered         = { bg = "#f7f7f7" }
preview_hovered = { bg = "#f7f7f7" }

# Find
find_keyword  = { fg = "#ededed", bg = "#aa5b00", bold = true }
find_position = { fg = "#07879d", bg = "#ebf2f6", bold = true }

# Marker
marker_copied   = { fg = "#387068", bg = "#387068" }
marker_cut      = { fg = "#f12465", bg = "#f12465" }
marker_marked   = { fg = "#9a4af3", bg = "#9a4af3" }
marker_selected = { fg = "#277add", bg = "#277add" }

# Tab
tab_active   = { fg = "#474747", bg = "#f7f7f7" }
tab_inactive = { fg = "#9d9da3", bg = "#ffffff" }
tab_width    = 1

# Count
count_copied   = { fg = "#474747", bg = "#38919f" }
count_cut      = { fg = "#474747", bg = "#c64343" }
count_selected = { fg = "#474747", bg = "#7890dd" }
# Border
border_symbol = "│"
border_style  = { fg = "#afafb6" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#9d9da3", bg = "#9d9da3" }

# Mode
mode_normal = { fg = "#ededed", bg = "#277add", bold = true }
mode_select = { fg = "#ededed", bg = "#9a4af3", bold = true }
mode_unset  = { fg = "#ededed", bg = "#7847bd", bold = true }

# Progress
progress_label  = { fg = "#5a5a5a", bold = true }
progress_normal = { fg = "#ffffff" }
progress_error  = { fg = "#f12465" }

# Permissions
permissions_t = { fg = "#277add" }
permissions_r = { fg = "#85683f" }
permissions_w = { fg = "#f12465" }
permissions_x = { fg = "#56713a" }
permissions_s = { fg = "#fefefe" }

[select]
border   = { fg = "#afafb6" }
active   = { fg = "#474747",  bg = "#cccccf" }
inactive = { fg = "#474747" }

# Input
[input]
border   = { fg = "#07879d" }
title    = {}
value    = { fg = "#7847bd" }
selected = { bg = "#cccccf" }

# Completion
[completion]
border   = { fg = "#07879d" }
active   = { fg = "#474747", bg = "#cccccf" }
inactive = { fg = "#474747" }

# Tasks
[tasks]
border  = { fg = "#afafb6" }
title   = {}
hovered = { fg = "#474747", bg="#cccccf" }

# Which
[which]
cols = 3
mask            = { bg = "#ededed" }
cand            = { fg = "#006d8f" }
rest            = { fg = "#277add" }
desc            = { fg = "#9a4af3" }
separator       = "  "
separator_style = { fg = "#87a5b6" }

# Notify
[notify]
title_info  = { fg = "#07879d" }
title_warn  = { fg = "#85683f" }
title_error = { fg = "#f12465" }

# Help
[help]
on      = { fg = "#56713a" }
run     = { fg = "#9a4af3" }
hovered = { bg = "#cccccf" }
footer  = { fg = "#474747", bg = "#ffffff" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#85683f" },

	# Media
	{ mime = "{audio,video}/*", fg = "#9a4af3" },

	# Archives
	{ mime = "application/*zip", fg = "#f12465" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f12465" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#006d8f" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f12465" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f12465" },
	{ name = "*", is = "exec"  , fg = "#56713a" },

	# Fallback
	{ name = "*/", fg = "#277add" }
]
    